package com.smartspend.service;

import com.smartspend.model.AI.AssistantChatBot;
import dev.langchain4j.memory.ChatMemory;
import dev.langchain4j.memory.chat.MessageWindowChatMemory;
import dev.langchain4j.model.chat.StreamingChatModel;
import dev.langchain4j.model.chat.response.ChatResponse;
import dev.langchain4j.model.chat.response.StreamingChatResponseHandler;
import dev.langchain4j.model.ollama.OllamaStreamingChatModel;
import dev.langchain4j.service.AiServices;
import dev.langchain4j.service.TokenStream;
import org.testcontainers.shaded.org.yaml.snakeyaml.tokens.Token;

import java.util.concurrent.CompletableFuture;

public class AIChatbotService {
    /**
     * the memory which will be used by the model
     */
    private final ChatMemory chatMemory = MessageWindowChatMemory.withMaxMessages(10);
    /**
     * the model which handles things like prompting and interacting with the LLM
     */
    private final StreamingChatModel model;
    private final AssistantChatBot assistantChatBot;
    // this is the path which currently serves the ollama application
    private final String MODEL_BASE_PORT = "http://localhost:11434";
    // this is the name of the model I'm currently running
    private final String MODEL_NAME = "qwen3.5:latest";

    /**
     * initializes both the model and the AI service connection for the model
     */
    public AIChatbotService() {
        model = OllamaStreamingChatModel.builder()
                .baseUrl(MODEL_BASE_PORT)
                .modelName(MODEL_NAME)
                .build();
        assistantChatBot = AiServices.builder(AssistantChatBot.class)
                .streamingChatModel(model)
                .chatMemory(chatMemory)
                .build();


    }

    /**
     * Prompts the model
     * @param prompt the prompt given to the model
     * @return A chatResponse object generated by the model
     */
    public ChatResponse prompt(String prompt){
        CompletableFuture<ChatResponse> future = new CompletableFuture<>();
        model.chat(prompt, new StreamingChatResponseHandler() {
            @Override
            public void onPartialResponse(String partialResponse) {
                System.out.println(partialResponse);
            }
            @Override
            public void onCompleteResponse(ChatResponse chatResponse) {
                future.complete(chatResponse);
            }

            @Override
            public void onError(Throwable throwable) {
                future.completeExceptionally(throwable);
            }
        });

        return future.join();
    }

    /**
     * Prompts the model to generate a tokenStream
     * @param message the prompt given to the model
     * @return A token stream object
     */
    public TokenStream GenerateTokenStream(String message){
        return assistantChatBot.chat(message);
    }
}
